apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-vaadin-crm
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-vaadin-crm
  template:
    metadata:
      labels:
        app: demo-vaadin-crm
    spec:
      containers:
        - name: demo-vaadin-crm
          image: demo-vaadin-crm:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: demo-vaadin-crm-balancer
spec:
  selector:
    app: demo-vaadin-crm
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
